name: PR Build and test

on: [pull_request]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          addHoldComment: "true"
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run pack
      - run: npm test
      # If something fails I want to set the status commit to "error" without adding anymore comments
      # I'm happy to leave the PR with `/hold` if there is an error
      - if: always()
        uses: ./
        with:
          addHoldComment: "true"
          status: "${{ job.status }}"
